### ISSUE TITLE
The RAW Denoise Checkpoint is missing

### ISSUE THREAD

**Issue by shuwei666** [q935970314/Deep-FlexISP#4]
![image](https://github.com/q935970314/Deep-FlexISP/assets/106613332/5c8ea81e-b356-4928-a22b-482c89d989b7)

Nice work!
Please provide the checkpoint for a thorough verificatioon.

**Comment by q935970314** [comment]
Thank you for your attention.
I uploaded the checkpoint, you can download it from Google Drive.
